version: '2.2'
networks:
  default:
    name: infrastructure-net
    external: true

services:
  redis-master:
    hostname: cardano.redis.master
    container_name: cardano-redis-master
    image: redis:7.0.5
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=redis_password
    command: redis-server
    ports:
      - "26301:6379"

  redis-slave:
    hostname: cardano.redis.slave
    container_name: cardano-redis-slave
    image: redis:7.0.5
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=redis_password
      - REDIS_PASSWORD=redis_slave_pass
    command: redis-server --slaveof redis-master 6379
    ports:
      - "26302:6379"
    links:
      - redis-master

  redis-sentinel:
    hostname: cardano.redis.sentinel
    container_name: cardano-redis-sentinel
    image: 'bitnami/redis-sentinel'
    environment:
      - REDIS_MASTER_HOST=${DOCKER_HOST_IP:-127.0.0.1}
      - REDIS_MASTER_PORT_NUMBER=26301
      - REDIS_MASTER_PASSWORD=redis_password
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=500
      - REDIS_SENTINEL_QUORUM=2
      - REDIS_SENTINEL_PASSWORD=redis_sentinel_pass
    ports:
      - "26379:26379"
    depends_on:
      - redis-master
      - redis-slave

volumes:
  redis-db:

