spring:
  application:
    name: as-service
  datasource:
    url: jdbc:mariadb://localhost:3306/as
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

server:
  port: 8001

logging:
  level:
    root: info

secret-key:
  app:
    jwtSecret: cong@chiend@u!2#
    jwtExpirationMs: 60000
    jwtRefreshExpirationMs: 1200000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/