spring:
  application:
    name: report-service
  datasource:
    url: jdbc:mariadb://localhost:3306/rpt
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
server:
  port: 8003


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

secret-key:
  app:
    jwtSecret: cong@chiend@u!2#

dubbo:
  application:
    name: ext
  registry:
    address: zookeeper://localhost:2181?timeout=100000
  scan:
    base-packages: com.example.rpt.service.dubbo
  consumer:
    check: false
  protocol:
    name: dubbo
    port: -1

kafka-ext:
  bootstrap-servers: localhost:29092
  zookeeper-hosts: localhost:2181
  topic-properties:
    name: ext_test
  thread-properties:
    num-of-consumer-default: 3
    num-of-consumer-max: 6
  consumer-properties:
    group-id: ext
